### ISSUE TITLE
Safari 14.1 default date control

### ISSUE THREAD

**Issue by timblanq** [mymth/vanillajs-datepicker#101]
Safari has implemented a default date/time control in their newest version. Mentioned in their [release notes](https://webkit.org/blog/11648/new-webkit-features-in-safari-14-1/). And I can't find a way to hide it yet. Does anyone has a solution for this? Maybe even a hot fix, until safari releases an easy css way to do it?!

Thanks in advance, guys!

**Comment by Leonick** [comment]
Set your input box to type="text" instead of "date".

**Comment by mymth** [comment]
According to the linked release notes,

> _the [date](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)(, ...) attributes for the input element prompt the browser to create date (...) controls_

I'll close this because it's not this library's issue.
