### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by varunmuriyanat** [mymth/vanillajs-datepicker#106]
[This package](https://www.jsdelivr.com/package/npm/vanillajs-datepicker) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by mymth** [comment]
I'll close this, as jsDelivr no longer shows this message.
