### ISSUE TITLE
[feedback] small suggestion for onClickTodayBtn()

### ISSUE THREAD

**Issue by DRocksCoding** [mymth/vanillajs-datepicker#11]
Very nice component!! Thanks for sharing it. I'm impressed by its quality and all the customization that's possible to change.

EDIT: I've been able to find a little something that might possibly be an improvement:
With settings like this:
```JavaScript
const elem = document.querySelector('#date__input');
const datepicker = new Datepicker(elem, {
    autohide: true,
    format:"d MM yyyy",
    language: "fr-CH",
    minDate: "1 Janvier 2019",
    maxDate: "31 Décembre 2022",
    todayBtn: true,
    todayBtnMode: 1, // select
    todayHighlight: true,
    weekStart: 0
});
```
I noticed that pressing the "today" button will not update the calendar view to what "today" corresponds to. For example, if you were in another month like May and then you choose "today", next time you open the calendar it will be displaying the month of May still.

Would it be a a good thing that today updates the view to "today" ?

BTW: Your code is really clean in my opinion this is a very good structure which is much easier to follow than many libraries I checked recently. So clean that it was easy to find where that action is happening and I could fix it just by changing render: false to true.

```JavaScript
    function onClickTodayBtn(datepicker) {
        const picker = datepicker.picker;
        if (datepicker.config.todayBtnMode === 1) {
            datepicker.setDate(today(), {render: true}); // <--- false becomes true and it works now
            if (datepicker.config.autohide) {
                datepicker.hide();
                return;
            }
        } else {
            picker.changeFocus(today());
        }
        picker.changeView(0).render();
    }
```

**Comment by mymth** [comment]
Thank you for the kind comment and feedback. This is actually a bug and will be fixed soon.

**Comment by DRocksCoding** [comment]
Nice thanks for the recent update!!
