### ISSUE TITLE
Support TypeScript and make headless UI

### ISSUE THREAD

**Issue by Abdulrahmanelheyb** [mymth/vanillajs-datepicker#115]
I want to use this package but it is not supported the TypeScript and I prefer to recommend making this project headless UI

**Comment by rougin** [comment]
Hello! As I checked now, the library is currently supporting Typescript in this opened issue: https://github.com/mymth/vanillajs-datepicker/issues/59

Regarding on the headless UI, it was stated in the documentation that you can integrate it with any framework you like: 
https://mymth.github.io/vanillajs-datepicker/#/?id=other-frameworks

**Comment by Abdulrahmanelheyb** [comment]
> Hello! As I checked now, the library is currently supporting Typescript in this opened issue: #59
> 
> Regarding on the headless UI, it was stated in the documentation that you can integrate it with any framework you like: https://mymth.github.io/vanillajs-datepicker/#/?id=other-frameworks

I mean in headless is; library has contain only logic without any style
