### ISSUE TITLE
[suggestion not a bug] allow 1-2 digit user inputs to automatically set day according to current month and year

### ISSUE THREAD

**Issue by DRocksCoding** [mymth/vanillajs-datepicker#12]
Hello @mymth,

I've been playing around with your great tool for a moment trying to implement some personal favorite features and I'd like to suggest it to you just in case you would like the idea too.

So basically I want to only need to enter 1 or 2 digits in the input field so that it will automatically set a new date string according the the current view month and year.
For example, you type "5" and it will insert 5 April 2020 because we are currently in the month of April inside the calendar view.
Then, if you switch to the month of June and you type "5" in the date input field this time, it would automatically set date to 5th of June 2020 because the calendar view is now set on June.

In the source code I was able to achieve it like so (almost surely a bad way because I'm still new to JavaScript):
```JavaScript
update(options = undefined) {
    if (this.inline) {
        return;
    }

    const opts = Object.assign({autohide: false}, options);

    // Try to allow 1-2 digits user inputs to automatically set date
    // according to view's current month.
    let reformattedUserInput = this.inputField.value.trim();
    if (reformattedUserInput && reformattedUserInput.length === 1 || reformattedUserInput.length === 2) {
        const currentMonth = this.picker.views[1].focused + 1;
        reformattedUserInput = reformattedUserInput + " " + currentMonth; // my date format is set to d MM yyyy (that's why I append a space)
    }
    const inputDates = stringToArray(reformattedUserInput, this.config.dateDelimiter);
    // const inputDates = stringToArray(this.inputField.value, this.config.dateDelimiter);

    const newDates = processInputDates(inputDates, this.config);

    //...
}
```

So if you have a few minutes and would like to comment on this idea, I'd be glad to have your feedbacks. Thanks :)

Alex

**Comment by mymth** [comment]
Hello Alex,

This kind of highly specific use case shouldn't be included in the module's program. You should implement your code in your application's program.

If I were in your situation, I would write the program like this:

```javascript
import {Datepicker} from 'vanillajs-datepicker';

class MyDatepicker extends Datepicker {
  update(options = undefined) {
    const inputVal = this.inputField.value.trim();
    if (inputVal && inputVal.length < 3) {
      const day = Number.parseInt(inputVal, 10);
      if (!isNaN(day)) {
        const newDate = new Date(this.picker.viewDate).setDate(day);
        const {format, language} = this.config;
        this.inputField.value = Datepicker.formatDate(newDate, format, language)
      }      
    }
    Datepicker.prototype.update.call(this, options);
  }
}

const elem = document.querySelector('#date__input');
const datepicker = new MyDatepicker(elem, {
  // some options...
});
```

Hope this example gives you helpful information to achieve your aim.

**Comment by DRocksCoding** [comment]
Thanks mymth,
It is very nice that you took this time and I really appreciate it! 

I never thought I could just extend the module, that is brilliant.
However I read on mdn classes again to double check my understanding but I am still unsure if the way it extends will override the original update method?
Would the extended code be executed in addition to the original method or would it get rid of all its content in favor of the extended code?

So let's say I want to keep everything intact in the original Datepicker update() method but only want to add an extra condition can you confirm that extending like so is the way to go?

Again, thank you so much.

**Comment by mymth** [comment]
I just noticed I wrote superclass's method call in old-fashioned (pre-ES6) way. And I think it made you confused.
I should have written `super.update(options)` instead of `Datepicker.prototype.update.call(this, options)`.

If you look at the `js/picker/views` directory, you can find a working example of Javascript class inheritance there.
If you google "javascript prototype chain", you can learn the underlying technology behind Javascript classes.

I think the best and quickest way to confirm is to write a test program yourself.

**Comment by DRocksCoding** [comment]
Well this was a deep dive in the darkest parts of JavaScript :D that prototype chain is going to change how I think about my objects structure.

I've been reading your use of super class too and I think I get it just enough to go test properly.
Thank you and have a good day.
