### ISSUE TITLE
Add function to set view date.

### ISSUE THREAD

**Issue by aydam2728** [mymth/vanillajs-datepicker#122]
Hi,

I really like your datepicker. I use it as a meal planner. Each time a user connects, I will look for the dates in a db. But the view is automatically on the last date. I would like the focus to be on today's date.

Do you think this feature is possible?

Thanks!

**Comment by smalos** [comment]
Use defaultViewDate?

https://mymth.github.io/vanillajs-datepicker/#/options?id=defaultviewdate

**Comment by aydam2728** [comment]
Isn't possible because I have some selected dates

**Comment by mymth** [comment]
Although the priority is not high, this is actually in my to-do list. So, I can't say when, but this feature will be added at some point in the future.
