### ISSUE TITLE
Max date based on another input value

### ISSUE THREAD

**Issue by joseehilton147** [mymth/vanillajs-datepicker#131]
It's possible to set max date dynamic based on another date value?

For example, I have input A, and comes with today date, but I change it to same day next month manually, clicking on date. 

Can I set max date on other's input based on input A value? 

Example: Max date pre-defined: today + 6 months, but I changed input A current date to today + 1 month, for example 01/01/2023, so I would like to set all others input's max date to be based on 01/01/2023 and not today date who got prefilled when page loaded.

**Comment by mymth** [comment]
This is an example code I wrote for #112. The basic idea should be the same.
https://codepen.io/mymth/pen/mdXrzZQ

**Comment by joseehilton147** [comment]
thank you
