### ISSUE TITLE
minDays?

### ISSUE THREAD

**Issue by dylanjohn** [mymth/vanillajs-datepicker#148]
Is it possible to set minimum days of the selected range? 

For example, I want start and end date at least 1 day apart..

**Comment by mymth** [comment]
I'm so sorry, but it's too unclear for me to get what you're trying. Are you having a problem with updating the min/maxDate dynamically with setOptions()?

Could you be more specific about what you've tried so far and where you see a problem?

**Comment by dylanjohn** [comment]
Hi, I would like to set the range that the start date and end date cannot be the same date but need to be at least 1 day difference.

e.g I can set the start date as 30/05/2023 then the end date must be 31/05/2023 or later..

**Comment by dylanjohn** [comment]
Sorry this is not a bug, im asking if this is currently possible with your library

**Comment by mymth** [comment]
#131 will be helpful.

**Comment by dylanjohn** [comment]
Thanks, much appreciated
