### ISSUE TITLE
Custom css for some days

### ISSUE THREAD

**Issue by bert126** [mymth/vanillajs-datepicker#152]
Would it be possible to add a custom CSS for specific cells? 
I'm thinking of putting a background color on a particular week. 

This exists for example in the following DP:
https://ng-bootstrap.github.io/#/components/datepicker/examples#customday

**Comment by mymth** [comment]
https://mymth.github.io/vanillajs-datepicker/#/options?id=beforeshowday

You can see a basic example on the [online demo](http://raw.githack.com/mymth/vanillajs-datepicker/v1.3.3/demo/index.html).
