### ISSUE TITLE
Date format "dd-mm-yy" results to wrong output

### ISSUE THREAD

**Issue by mm-georges** [mymth/vanillajs-datepicker#155]
Hello,

I'm having issues setting the date format to "dd-mm-yy" in the Datepickerconfig. Selecting a date always results to the year 23 instead of 2023.
Is this a known Issue? Any help appreciated. Thank you 

Output: 
Sat Jul 29 0023 00:00:00 GMT+0053 (Mitteleuropäische Sommerzeit)

Expected Output:
Sat Jul 29 2023 00:00:00 GMT+0053 (Mitteleuropäische Sommerzeit)

Config:
```json 
datepickerConfig: {
        language: 'de',
        weekStart: 1,
        format: 'dd.mm.yy',
        days: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
        daysShort: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
        daysMin: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
        months: [
            'Januar',
            'Februar',
            'März',
            'April',
            'Mai',
            'Juni',
            'Juli',
            'August',
            'September',
            'Oktober',
            'November',
            'Dezember',
        ],
        monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        today: 'Heute',
    },
```

**Comment by haagtobias** [comment]
I am also experiencing this issue, but it only appears when 
1. I select a date, let's say `29.07.2023`
  a. **correct** date `Sat Jul 29 2023 00:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)` is fired as event
2. then I click outside of the datepicker and
  a. **incorrect** date `Sat Jul 29 0023 00:00:00 GMT+0053 (Mitteleuropäische Sommerzeit)` is fired as event

Expected Output:
`Sat Jul 29 2023 00:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)`

This also happens when I select a date, reopen the datepicker, select the same date aswell and click outside. Maybe originating from the "main"-bug.

**Comment by mymth** [comment]
Please read the notes in here: https://mymth.github.io/vanillajs-datepicker/#/date-string+format?id=date-format

2 digit year notation is not supported by the built-in parser. If you want to use it, you need to make a custom parser using 2→4 digit year conversion with century mapping that fits your use case. For example:

```javascript
new Datepicker(element, {
  format: {
    toValue(dateStr) {
      const date = new Date(Datepicker.parseDate(dateStr, 'd.m.y', 'de'));
      const year = date.getFullYear();
      date.setFullYear(year + (year < 50 ? 2000 : 1900));
      return date;
    },
    toDisplay(date) {
      return Datepicker.formatDate(date, 'dd.mm.yy', 'de');
    },
  },
  language: 'de',
});
```
You may be able to make the parser simply like this:

```javascript
toValue(dateStr) {
  const fullDateStr = dateStr.replace(/\.(\d+)$/, '.20$1');
  return new Date(Datepicker.parseDate(fullDateStr, 'd.m.y', 'de'));
},
```

I admit it's less noticeable in the docs. Initially, there was a note reading "format only" in the table of tokens, but it looks that I deleted it for some reason and forgot to put back. So, I'll update the docs.

@haagtobias you'll understand what is happening if you try setting `updateOnBlur: false` option temporarily.

**Comment by mm-georges** [comment]
Perfect, works for me! Thank you~ 😃
