### ISSUE TITLE
AssumeNearbyYear function?

### ISSUE THREAD

**Issue by sanchawebo** [mymth/vanillajs-datepicker#163]
Trying to replace bootstrap-datepicker with this lib. After scanning through the docs/demo i couldn't find a `assumeNearbyYear` functionality.

> assumeNearbyYear
> Boolean or Integer. Default: false
> 
> If true, manually-entered dates with two-digit years, such as “5/1/15”, will be parsed as “2015”, not “15”. If the year is less than 10 years in advance, the picker will use the current century, otherwise, it will use the previous one. For example “5/1/15” would parse to May 1st, 2015, but “5/1/97” would be May 1st, 1997.
> 
> To configure the number of years in advance that the picker will still use the current century, use an Integer instead of the Boolean true. E.g. “assumeNearbyYear: 20”
> [source](https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#assumenearbyyear)

Is there something like it in this lib?
Greetings

**Comment by mymth** [comment]
Please see https://github.com/mymth/vanillajs-datepicker/issues/155#issuecomment-1647060565
