### ISSUE TITLE
Clarification about date range picker options

### ISSUE THREAD

**Issue by ker0x** [mymth/vanillajs-datepicker#166]
Hello,

I'm co-maintening [DefinitelyTyped/vanillajs-datepicker](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/vanillajs-datepicker) to be able to use this library with typescript and I would like some clarifications about options for the date range picker class.

Does [DateRangePickerOptions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vanillajs-datepicker/DateRangePicker.d.ts#L3) should extend [DatepickerOptions ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vanillajs-datepicker/Datepicker.d.ts#L35)?

Thanks in advance

**Comment by mymth** [comment]
I think so because it's a mix of range-specific options used by the DateRangePicker object itself and ones of DatepickerOptions to be passed to its child Datepicker objects, and should accept both types of options.

**Comment by ker0x** [comment]
Thanks for the clarification 👍!
