### ISSUE TITLE
Plans for bootstrap@5.3 support ?

### ISSUE THREAD

**Issue by martinbarilik** [mymth/vanillajs-datepicker#169]
Any plans ?

![image](https://github.com/mymth/vanillajs-datepicker/assets/58255651/ed2922dc-4a4f-410e-a60d-69056cb5cef9)

I am unable to upgrade to bootstrap without having vanilla datepicker being compatibile :) 

Cheers

**Comment by mymth** [comment]
Please see #146, https://github.com/mymth/vanillajs-datepicker/blob/master/CHANGELOG.md#133
Which version are you using?

**Comment by mymth** [comment]
Duplicate of #146
