### ISSUE TITLE
toggle picker when icon is clicked

### ISSUE THREAD

**Issue by jgueldner** [mymth/vanillajs-datepicker#177]
Hello, thank you for your efforts on the datepicker. I have a query regarding toggling the datepicker by clicking an icon (the red thing).

![ datepicker](https://github.com/mymth/vanillajs-datepicker/assets/79506238/dfd3344c-9e1e-41ac-b3c8-52bfb47949d4)

Currently, I have positioned the icon within a slot as follows:
```
<custom-text-input>
  <custom-icon slot="datepicker-icon"></custom-icon>
</custom-text-input>
```

My intention is to display the datepicker only when the icon is clicked. However, the document listener triggers each time, causing unintended behavior. Additionally, when the picker is already open and I click on the icon, it briefly unfocuses (due to the listener on the document) and then calls my own toggle() function. Consequently, this.datepicker.show() is invoked, leading to the datepicker being displayed again, resulting in the same state as before.

Furthermore, I would like clicking inside the text-input to focus without opening the picker.

The current options I'm utilizing are as follows:

```
this.datepicker = new ExtendedDatepicker(this.inputElement, {
  autohide: true,
  language: 'de',
  maxView: 2,
  showOnFocus: false,
  showOnClick: false,
  todayHighlight: true,
  updateOnBlur: true,
  weekStart: 1,
  nextArrow: '<custom-icon icon="datepicker-picker-arrow-right"></custom-icon>',
  prevArrow: '<custom-icon icon="datepicker-picker-arrow-left"></custom-icon>',
  minDate: minDate,
  maxDate: maxDate,
}, this.textInput);
```

I hope this explanation is clear. Any guidance on how to address this issue would be greatly appreciated. 
Thank you so much!

**Comment by mymth** [comment]
The document listener is for the `mousedown` event, not `click`. So, if you add a `mousedown` event listener to the icon in addition to the `click` listener, and call `event.stopPropagation()` in it, I think the second (unable-to-close) part will probably be solved.

Regarding the first part, could you give me the details of the "unintended behavior"?

As for the third part, did you mean that the picker opens on the input element's getting focused even though the `showOnFocus: false`,  `showOnClick: false` options are set?

**Comment by jgueldner** [comment]
Hi, thanks for your quick response! The `mousedown` event listener was the culprit as I didn't set it on the icon correctly. Now with the `showOnFocus: false` and `showOnClick: false` it works like a charm! Thanks a lot :)
