### ISSUE TITLE
Problem with classes in datepicker button with Bootstrap 5

### ISSUE THREAD

**Issue by DigitalAndSEO** [mymth/vanillajs-datepicker#188]
Hi team,
First of all, congratulations on the work!
I wanted to tell you that I have been able to verify that when a button is used to open the datepicker, when the div is generated with classes "datepicker datepicker-dropdown datepicker-orient-left datepicker-orient-bottom" the upper buttons do not have the btn class, which makes it look like this:

<img width="265" alt="Captura de pantalla 2024-06-27 a las 21 27 34" src="https://github.com/mymth/vanillajs-datepicker/assets/35368872/80398b7f-ac2d-467d-83cc-c1e51a1d4471">
<img width="631" alt="Captura de pantalla 2024-06-27 a las 21 28 09" src="https://github.com/mymth/vanillajs-datepicker/assets/35368872/fe46b17e-e5ba-4dc1-ab73-14f79cf72524">

If I add the "btn" class in the code inspector, it is perfectly integrated:

<img width="266" alt="Captura de pantalla 2024-06-27 a las 21 28 52" src="https://github.com/mymth/vanillajs-datepicker/assets/35368872/ee49a655-d38a-49fe-b539-720169e91a27">
<img width="664" alt="Captura de pantalla 2024-06-27 a las 21 28 42" src="https://github.com/mymth/vanillajs-datepicker/assets/35368872/65e9e47f-2ed1-4358-8fdf-6d2a15ef1d1d">

More than anything so that you can check it and if it is an error, add it in a new version.
Right now I am adding it myself via JS, but I think it would be good for the project to have this added natively.

**Comment by mymth** [comment]
If you haven't, please read No. 1 of https://mymth.github.io/vanillajs-datepicker/#/?id=other-frameworks and https://mymth.github.io/vanillajs-datepicker/#/?id=bootstrap. It may be even better if you also check what [Bulma's](https://bulma.io/documentation/elements/button/) and [Foundation's](https://get.foundation/sites/docs/button.html) button classes are. You'll probably be able to have better understanding why you need to do it yourself via JS.

As stated in README, this library is made neither dedicated to nor primarily for Bootstrap. And I have no intention of hard-coding something specific to a particular framework into the JS programs.

**Comment by DigitalAndSEO** [comment]
All perfect. Thanks
