### ISSUE TITLE
defaultViewDate

### ISSUE THREAD

**Issue by greatgraphicdesign** [mymth/vanillajs-datepicker#19]
Hello! Is there an option setting that can address this? I'm thinking perhaps `defaultViewDate`, but I don't know what setting would fix the following issue for date range calendars...

Today is April 23. Therefore, my start calendar opens in April as expected. However, if I select a start date in May and open the end calendar, it also opens in April. I'm expecting May. But what's worse is that when I click forward to get to May, the calendar skips May and goes straight to June. We have to click backward from June to get to May. It's a bit disorienting.

I'd love to see the defaultViewDate set to "today() or start date if selected". I'm not sure what's causing the calendar to skip from April to June, but maybe this could be addressed with this change.

Once again, I wholeheartedly appreciate this tool. Thank you so much for creating and sharing it!

**Comment by mymth** [comment]
This is because of the same bug as #17. It's a bug that causes the calendar not to be redrawn in some situations. (#11 is also related to this bug.) So, when #17 is fixed, this should be fixed too.

**Comment by greatgraphicdesign** [comment]
Thank you. :)
