### ISSUE TITLE
How to use inside a <dialog> element?

### ISSUE THREAD

**Issue by Sleepful** [mymth/vanillajs-datepicker#190]
It seems that datepicker HTML node is appended at the root of the document, however <dialog> elements only visibly display elements that are its own child nodes.

How do I make it such that I can use datepicker inside Dialog?

**Comment by Sleepful** [comment]
Might be an issue with this other library I am using:

https://github.com/themesberg/flowbite-datepicker

**Comment by mymth** [comment]
That's the behavior of v1.1.x and earlier. It's no longer the case for this library.
(see https://github.com/mymth/vanillajs-datepicker/blob/master/CHANGELOG.md#120)

You might be able to use the `container` option.

**Comment by Sleepful** [comment]
Thank you! I will close this issue.
