### ISSUE TITLE
disableTouchKeyboard still displays keyboard on month change

### ISSUE THREAD

**Issue by mitgolden76** [mymth/vanillajs-datepicker#3]
With disableTouchKeyboard set to true, the touch keyboard does not display upon initial focus on the input element, but the keyboard does display when selecting next or previous month on a mobile device. Ideally, the keyboard would not display when changing months if disabled. This is being observed on Chrome v80.0 and Firefox v68.6 on Android on the live demo as well as my own plain CSS implementation.

**Comment by mitgolden76** [comment]
The same behavior occurs when a date is selected, even when it is configured to accept multiple dates.

**Comment by evromalarkey** [comment]
you can use attribute inputmode="none" on input if you don't want to see keyboard on mobile
