### ISSUE TITLE
custom titleFormat

### ISSUE THREAD

**Issue by Gruski** [mymth/vanillajs-datepicker#32]
The current titleFormat is a constant set to "MM y". I would like to change it to "M y". Of course I can do this by changing the source and then the min version but can this be made a publicly set prop so I and maybe others don't have to modify the code for every new release?

**Comment by mymth** [comment]
It can be done through locale. (not intuitive, though...)

```javascript
const myEn = {titleFormat:'"M y'};
Object.assign(Datepicker.locales, myEn);

const datepicker = new Datepicker(el, {language: 'myEn'});

// or you can override the default en locale

Datepicker.locales.en.titleFormat = 'M y';
const datepicker = new Datepicker(el);
```

I'm sorry I answered you wrong in the past issue.

**Comment by Gruski** [comment]
That worked. Thanks.
