### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by lofwyr14** [mymth/vanillajs-datepicker#37]
It would be nice to see a Bootstrap 5 (currently alpha) support. 
The first step for migration is:

- replace "color-yiq" with "color-contrast" in the scss file.

**Comment by brianzinn** [comment]
Did you make any progress on that @lofwyr14?  I think Bootstrap 5 stable comes out this month :)

Ended up here and with your `color-yiq` replacements but still many CSS classes missing:
```
<style lang="scss" scoped>
@import '../../node_modules/bootstrap/scss/_functions.scss';
@import '../../node_modules/bootstrap/scss/_variables.scss';
@import '../../node_modules/bootstrap/scss/_mixins.scss';
@import '../../node_modules/vanillajs-datepicker/sass/datepicker-bs4.scss';
</style>
```

Ended up just importing the bs4 css from the dist folder and it's usable...

**Comment by gentleboy98** [comment]
Regarding the _**Error: $color1: color-yiq(#f8f9fa) is not a color.**_

As suggested by @brianzinn, it compiles fine with 

`@import "path/to/node_modules/vanillajs-datepicker/dist/css/datepicker-bs4";`
