### ISSUE TITLE
minDate not working

### ISSUE THREAD

**Issue by ThomasAggerholm** [mymth/vanillajs-datepicker#41]
Hello,
Thank you for this great library.

I do have a minor issue. The minDate doesn't work. I tried to set it to today's date, but all previous dates remain active.

**Comment by ThomasAggerholm** [comment]
Somehow this is working now :-)

**Comment by RavenWits** [comment]
I am currently having the same issue how did you managed to work that out?

**Comment by ThomasAggerholm** [comment]
I just assigned minDate to new Date() and it worked

**Comment by RavenWits** [comment]
> I just assigned minDate to new Date() and it worked

Actually I've done the same thing but it still works as maxDate and it disables all the dates beginning from today and all past dates still remains active.

**Comment by RavenWits** [comment]
Thanks for sharing :)

**Comment by nereolopez** [comment]
Hi, 

I am struggling to get the `datesDisabled` working. 

1. If I try to use your example it will not work as on v1.2.0 it only admits an array of strings (not dates). 
2. If I pass a hardcoded array of string dates like `[2022-03-24]` it will still not disable the day in the calendar

The only way I managed to have it working was using an example I found in[CodeSandbox](https://codesandbox.io/s/date-checker-forked-ehe1lf) and modifying it as per the screenshot below
![image](https://user-images.githubusercontent.com/5878234/158074867-ca8021ff-a1c2-4297-8c67-b49f0b2b68d3.png)
When I try that in my project the calendar is not disabling the days marked to be disabled. I tried same code as in the screenshot and also hardcoding dates in all possible formats in case it was related to the locale...

The only difference I see with the live example linked above is that it uses v1.0.2 while I am in v1.2.0

Any hint is more than welcome. Thanks!

**Comment by mymth** [comment]
I recommend you to check what `new Date(Date.now).toDateString()` results and see if it matches the format set to the date picker.

**Comment by nereolopez** [comment]
Hi, just in case someone else faces the same, I finally managed to disable dates using the `beforeShowDay` instead. I do not have any issues with the format of my dates there. So, every time a day is going to be painted in the calendar, this callback gets executed and there I return the `{ enabled: isEnabled }` based on if the date the cell to be painted represents is one of the dates I have in my string array (with this format as shared in my previous comment: `[2022-03-24]`)of dates to be disabled. It does the trick, but not sure if in terms of performance being able to assign that string array directly to the `datesDisabled` and have it working would be better.
Cheers!
