### ISSUE TITLE
onClickOutside : return/ignore when inactive

### ISSUE THREAD

**Issue by JocoLabs** [mymth/vanillajs-datepicker#45]
To start, thanks for all the hard work.

I have the datepicker implemented in a component, so there is a live instance most of the time.

With every click outside the input, it keeps firing the ui update code (which calls the custom formatter).

if possible, toss in at the top of the event handler
js/events/otherListeners.js: line 5

if ( !datepicker.active ) return;

Unless i am missing something, i dont think anything needs to happen behind the scenes when the picker is not active.

Also, during debugging, when the custom toValue formatter was called, it would call twice.
One call with date === 'Dec 26th' and a second call with date === '2020'
(which was giving me some getFullYear is not defined errors).

I found a better way to write my component, so i no longer have this issue (with toValue), this is more of an FYI.

Thanks again!
-Joe

**Comment by mymth** [comment]
Thank you for your feedback.

For the first point, you are right. There is no need to do anything when the picker is hidden.
For the second point, the first call is for input field and the second one is for the view switch label. But definitely the view switch doesn't have to be updated on every change of the date.

I'll include the fixes for these in the next update.

**Comment by JocoLabs** [comment]
Great!

No rush at all (i manually patched my copy with the submitting fix).

It is new years, get some rest.
