### ISSUE TITLE
DateRangePicker - Upgrading from 1.0 to 1.10

### ISSUE THREAD

**Issue by pmarciniuk** [mymth/vanillajs-datepicker#46]
Hi,

I've been using the DateRangePicker v1.0 and everything was working fine. I have the simplest implementation ever. As per documentation, a container with 2 input elements inside. 
I've decided to go for the latest version as I really need the new feature that been added (updateOnBlur).

I've replaced the source files (I'm using the `From Browser` implementation [link](https://mymth.github.io/vanillajs-datepicker/#/?id=using-from-browser)). I didn't change my implementation and it just stopped to work. I reviewed the changelog and I can't see any breaking changes with the implementation. I reviewed the documentation and went through the source code. Looks like there is a problem with Datepicker instance while using the Date Range Picker. Could you please review it? Those are the errors that I'm getting.

<img width="1053" alt="Screenshot 2020-12-29 at 18 38 38" src="https://user-images.githubusercontent.com/27367131/103306557-beb8b500-4a05-11eb-9be1-bf1f639b24f0.png">
<img width="1058" alt="Screenshot 2020-12-29 at 18 38 44" src="https://user-images.githubusercontent.com/27367131/103306560-c11b0f00-4a05-11eb-88f0-a08d36941db7.png">

Thank you!

**Comment by mymth** [comment]
I'm sorry it's a bug. In Datepicker constructor, I wrote a code to check the class of passed range picker object without importing the DateRangePicker class. But I just noticed it doesn't work when minified.
I'll fix it ASAP.

For a temporary solution, could you use un-minified version until the fix is released?
```html
<script src="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.1.0/dist/js/datepicker-full.js"></script>
```

Sorry for the inconvenience.

**Comment by pmarciniuk** [comment]
Please update in this issue when it's ready. Thank you!

**Comment by mymth** [comment]
The new v1.1.1 that includes this fix has just been released.
