### ISSUE TITLE
Form submit by click on prev and next month buttons

### ISSUE THREAD

**Issue by KonradRolof** [mymth/vanillajs-datepicker#48]
Hi,

the buttons to switch between the months are missing the type attribute. So when you click on a button a form submit is triggered. My current workaround for this is to search all buttons in the inline datepicker DIV and add the type.

```javascript
import nodeEach from "../helper/_node-each.function.js";

const container = document.querySelector(".js--get-datepicker");
const dp = new Datepicker(container, {
  format: "dd.MM.yyyy",
  language: "de",
  todayBtn: false,
  todayHighlight: false,
});

const buttons = container.querySelectorAll("button");
nodeEach(buttons, (button) => button.setAttribute("type", "button"));
```

But it would be nice if the type "button" would be set by the script itself.

**Comment by mymth** [comment]
Thank you for the bug report. I'll fix it soon.
