### ISSUE TITLE
Date format in header

### ISSUE THREAD

**Issue by Gruski** [mymth/vanillajs-datepicker#5]
When date format is set to 'mm/dd/yy' for input element it also changes the year selection buttons and header format to two digits which looks weird. Header shows "May 20" instead of "May 2020" which looks like your talking about the 20th of May instead of May 2020. Year in calendar should always display in four digit format regardless of input format or at least make it a separate configurable option.

**Comment by mymth** [comment]
I have to admit it's confusing and not stated noticeably in [the documents](https://mymth.github.io/vanillajs-datepicker/#/date-string+format), but currently, parsing 2-digit year is not supported and the 'yy' token can only be used for formatting.
Regardless of the number of `y`s in the format string, the built-in parser takes the year part as full year. So, if you provide a date string: '04/21/20', the selected date in ISO format will be _'0020-04-21'_, not '2020-04-21'. 

The header's format is hard-coded to `MM/y` (full month name and full year without leading zeros). When you see 'April 20' in the header, the selected month in ISO format is _'0020-04'_, not '2020-04'.

Adding 2-digit year parsing is one of my to-do list items, but no schedule has been decided yet.

A workaround to handle 2-digit year for now is using custom parser/formatter functions with the `parseDate()`,`formatDate()` static methods like below.

```javascript
{
  format: {
    toValue(date) {
      const fullYearDate = date.replace(/\/(\d\d)$/, '/20$1');
      return Datepicker.parseDate(fullYearDate, 'mm/dd/yyyy');
    },
    toDisplay(date) {
      return Datepicker.formatDate(date , 'mm/dd/yy');
    },
  },
}
```

**Comment by Gruski** [comment]
Thanks
