### ISSUE TITLE
Close datapicker on 'click outside'

### ISSUE THREAD

**Issue by vibonacci** [mymth/vanillajs-datepicker#52]
Hi,

Is there an option to close the datepicker without selecting an actual date, just by clicking outside of the picker?

**Comment by mymth** [comment]
If you press the Esc key, the picker hides without leaving the input field. You can re-show the picker by pressing the Esc key again.

I'm not sure the point of your question. What are you trying to do?

**Comment by vibonacci** [comment]
Sorry, I realize now what is going.

I have a separate 'open date picker' button, which used datepicker.show() from your API. When you use it like that, the associated input field is not focused, which leads to the issue that if you click 'outside' of the datepicker, it won't close.

**Comment by mymth** [comment]
Oops, this is a bug. I'll fix it soon.
