### ISSUE TITLE
Orientation option for vertical placement gives unwanted behavior with 'auto'

### ISSUE THREAD

**Issue by JerBlo** [mymth/vanillajs-datepicker#54]
Currently, you can set the orientation options for vertical placement on 'top', 'bottom' or 'auto' (see https://mymth.github.io/vanillajs-datepicker/#/options?id=orientation)

However, the 'auto'-option by default will place the datepicker as 'top'. The online example of the datepicker places the datepicker on the bottom and I think that should be the preferred position.

Is the preference for top-placement by purpose, or is this an issue in the current code? If so, we are happy to help!

**Comment by mymth** [comment]
It's an inheritance from bootstrap-datepicker. I just copied the algorithm so that the picker is positioned in the same way. Since the same mismatch can be seen in bootstrap-datepicker's docs, I didn't care much about it.
So it's kind of intentional.(not really a strong intention, though.)

**Comment by JerBlo** [comment]
Thanks for your reply. I indeed see the same 'issue' there. A 'prefer-bottom' option could be a nice addition, or maybe in the online example, there can be added some content on the top, so the default behavior can be shown there?

**Comment by mymth** [comment]
I agree that default-bottom is more natural. The decision to keep it the same was to focus on more fundamental features. So  it does't really have to be the same.
I'm thinking about making some changes to the way to display the picker in the next version. It would be a good opportunity to flip the default.

**Comment by GittyLover** [comment]
Dear mymth,

is it possible to make vanillajs-datepicker work with **popper.js.org** (also used in bootstrap 4) for the **placement**?
This would be very great for better **mobile suitability**! :)

Best reagards
