### ISSUE TITLE
Could it be possible to add a MutationObserver to watch for removed datepickers?

### ISSUE THREAD

**Issue by micabal** [mymth/vanillajs-datepicker#62]
Version used: v1.1.4

The problem:
Multiple datepickers keeps getting appended to body on same page and single page app

The situation:
I have 10 datepickers on a same page. 
It works fine.
I go to another page and then I come back. Now I have 10x2 datepickers (html) appended to the body.
It still works fine.

The suggestion for improvement:
Could it be possible to add a MutationObserver to watch for removed datepickers ?
Thus, if the element or a parent is removed, the code is kept clean.
Something like https://stackoverflow.com/a/44937162/5519544

My code:
I am not good enough to suggest any clean coding improvement.. Sorry 😅

PS: Many thanks for this amazing project. I was using the Bootstrap jQuery not long ago 😁

**Comment by mymth** [comment]
I don't think libraries (in general) should/need to clean their stuff up themself. I think it's app's responsibility to call lib's destroy()/clean()/etc. because it's app who calls lib's constructor/factory function/etc.
And this library is no exception.

**Comment by micabal** [comment]
For a SPA, having many datepickers code appended directly to body can be cumbersome to clean. Obviously I can manage the cleaning by myself, but it would ease the integration if the cleaning was made by itself.

Maybe, the `datepicker-dropdown` could be appended to the parent element of the input. I did a few tests and it seems to work properly. This solution would solve the issue for SPA that append code in a container div, descendant of the `body` tag. 

If you think my comment is irrelevant, feel free to close this issue. I have less experience than you so I'll follow your lead.

**Comment by mymth** [comment]
Why do you think cumbersome? I think there should be no issues If app does something similar to this.
```javascript
function switchPages(app, newPageObj, oldPageObj) {

  // ... some closing stuff for the old page

  oldPageObj.datepickers.forEach((datepicker) => {
    datepicker.destroy();
  });
  delete oldPageObj.datepickers;

  // ... other closing stuff

  // ... some opening stuff for the new page

  newPageObj.datepickers = Array.from(newPageObj.element.querySelectorAll('input.date'))
    .map(elem => new Datepicker(elem));
  
  // ... other opening stuff

  app.container.replaceChild(newPageObj.element, oldPageObj.element);
}
```

I'm actually planing to change the default container from body to the input's parent element in the next update for better support for cases like #50. You will be able to omit calling destroy() without issues, but I think it would still be better to do like the above for better readability.
