### ISSUE TITLE
Update for Bootstrap 5

### ISSUE THREAD

**Issue by castellinosoftware** [mymth/vanillajs-datepicker#70]
Good morning.
I have updated the project to introduce the new Bootstrap 5 framework.
Basically there is only one change to apply, the color-yiq bs4 function has been renamed to color-contrast in bs5.
I added some files in order to keep the css for both bs4 and bs5.
Can i do a pull request?

**Comment by mymth** [comment]
Of course you can. There's no need to ask because I can't review your code until you submit it.

**Comment by BariqDharmawan** [comment]
Please make the PR, I would love to wait and try it immediately on my project :)
