### ISSUE TITLE
autohide not working when click outside datepicker

### ISSUE THREAD

**Issue by arezascarlet** [mymth/vanillajs-datepicker#72]
cant hide when click outisde datepicker or out focus input, only working if click date

im testing in firefox and bootstrap 5

**Comment by mymth** [comment]
I'm unable to reproduce the problem.
https://codepen.io/mymth/pen/NWpMVVP

I guess something executed before calling `new Datepicker()` may be adding a mousedown event listener that cancels the event or stops bubbling up to `<body>`.

**Comment by arezascarlet** [comment]
i have solution for my problem.

i added another function for that problem

`document.addEventListener('click', function(event){
		if(document.activeElement !== elem){
			datepicker.hide()
		}
	});`
