### ISSUE TITLE
Npm package update

### ISSUE THREAD

**Issue by castellinosoftware** [mymth/vanillajs-datepicker#73]
Hi.
Is there an update date for the vanillajs-datepicker npm package?
I import vanillajs-datepicker into a bootstrap 5 based project and so I would need the latest version with bootstrap 5 support.

**Comment by castellinosoftware** [comment]
Is there any news on a new release?
For now, for those with my same problem, I solved it by importing the package directly from the master branch of github:
"dependencies": {
  ...
  "vanillajs-datepicker": "github:mymth/vanillajs-datepicker#master"
}

**Comment by mymth** [comment]
I'll close this as the new version was released.
