### ISSUE TITLE
Input field should not lose focus when clicking on picker

### ISSUE THREAD

**Issue by xdev1** [mymth/vanillajs-datepicker#85]
It looks really odd that the input field loses focus for a short moment when you click somewhere on the picker.
This seems to be easily fixable:

1. In file `pickerListeners.js` add the following function:

  ```js
    export function onMouseDownPicker(ev) {
      ev.preventDefault();
    }
  ```
2. In file `Picker.js` import also `onMouseDownPicker` and register it:

   ```js
      ...

      import {
        ...
        onMouseDownPicker
      } from '../events/pickerListeners.js';
      
      ...

          registerListeners(datepicker, [
             ...
             [element, 'mousedown', onMouseDownPicker],
             ...
          ]);
    ```

@mymth Please let me know what you think of this enhancement. I could prepare a PR if you like.

**Comment by mymth** [comment]
I din't think seriously to solve it because it's bootstrap-datepicker behavior. But thunks, this seems like giving me a hint for the solution of #78

**Comment by xdev1** [comment]
Okay, thanks for the info. This is something that can also be done in userland, in case someone (like me :wink:) does not like the above mentioned vannillajs-/bootstrap-datepicker behavior.
So I will close this issue.

**Comment by mymth** [comment]
Sorry, It looks like one of the typos I made made you misunderstand. I meant "I didn't think seriously...", not "I don't think seriously..." So I'm willing to make this change.
I think bootstrap-datepicker's this behavior is not intentional and there's no need to follow.
I'll reopen this for my tracking purpose.

**Comment by xdev1** [comment]
@lubomirblazekcz Could you please do me a favor and check whether the little changes mentioned in the issue description above have any negative impact on your time selector extension here: https://github.com/mymth/vanillajs-datepicker/issues/25#issuecomment-937671843
Many thanks.

**Comment by lubomirblazekcz** [comment]
@xdev1 seems to be ok 👍

**Comment by lubomirblazekcz** [comment]
@xdev1 ok maybe not after all, but it can be easily fixed

I've created new PR https://github.com/mymth/vanillajs-datepicker/pull/92 to resolve my issues with timepicker extention

I've edited your code a little to work with that change

`pickerListeners.js` (maybe `!datepicker.inline` should be there too, doesn't need to be for inline picker)
```js
export function onMouseDownPicker(datepicker, ev) {
  if (!ev.target.matches(datepicker.config.focusIgnoredSelector)) {
    ev.preventDefault();
  }
}
```

`Picker.js`
```js
registerListeners(datepicker, [
    ...
    [element, 'mousedown', onMouseDownPicker.bind(null, datepicker)],
    ...
 ]);
```

**Comment by xdev1** [comment]
@lubomirblazekcz 

Wouldn't the following changes work for your time field extension (I think this should also solve #78)?

1. Perform the modifications as written in the issue description above.

2. Remove the following lines - I do not think we need them any longer now:
    https://github.com/mymth/vanillajs-datepicker/blob/fefcf3c71ab4bb04f3b51d3fbb6609930658f8e8/js/events/pickerListeners.js#L66-L70
    https://github.com/mymth/vanillajs-datepicker/blob/fefcf3c71ab4bb04f3b51d3fbb6609930658f8e8/js/picker/Picker.js#L17
    https://github.com/mymth/vanillajs-datepicker/blob/fefcf3c71ab4bb04f3b51d3fbb6609930658f8e8/js/picker/Picker.js#L139

4. Now for your time input element you have to do something like:
    ```js
        timeInputElement.addEventListener('mousedown', (ev) =>
          ev.stopPropagation();
        );
    ```
 
Or am I missing something?

**Comment by lubomirblazekcz** [comment]
@xdev1 yeah that works even better, nice. Solves #78 and #92 isn't needed anymore
