### ISSUE TITLE
`getWeek(date)` should be customizable

### ISSUE THREAD

**Issue by xdev1** [mymth/vanillajs-datepicker#90]
Different countries can use different strategies to calculate the week of the year (aka. calendar week number).

Please compare week 1 and week 2 of 2017:

- United States:
   https://savvytime.com/week-number/united-states/2017

- United Kingdom:
   https://savvytime.com/week-number/united-kingdom/2017

Currently `vanillajs-datepicker` always uses (hard-coded => not customizable!) the ISO 8601 standard for calculating the calendar weeks:
https://github.com/mymth/vanillajs-datepicker/blob/fefcf3c71ab4bb04f3b51d3fbb6609930658f8e8/js/lib/date.js#L67-L74

Therefore it is currently not possible to show proper calendar week numbers for e.g. the United States (as they do not use the above mentioned ISO standard):

![image](https://user-images.githubusercontent.com/86223516/139723842-6a9c9ca7-17e3-4e1e-8dc4-31848f124fbe.png)

My proposal would be to enhance the `options` object with an optional `getCalendarWeek` parameter (type `undefined | ((timestamp: number, weekStart: number) => number)`) where the strategy for calculating the calendar weeks can be customized.
This is not a big deal to implement (less than 10 LOCs I guess + unit tests + documentation). I could prepare a PR if you want.

**Comment by xdev1** [comment]
@mymth 
BTW: If `weekStart` is **not** equal `1` (Monday) then the calculation of the calendar week numbers is not correct:

![image](https://user-images.githubusercontent.com/86223516/140498413-21c54267-e3e9-4ff0-89a7-1861f04dc1b6.png)

I think these lines here

https://github.com/mymth/vanillajs-datepicker/blob/9de5051545626b116db3d213b0b1e429f296967c/js/picker/views/DaysView.js#L142-L143

should be replaced with:

```js
 const startOfWeek = dayOfTheWeekOf(this.first, 1, this.weekStart); 
```

Correct?

**Comment by xdev1** [comment]
@mymth Please be aware that it seems that I've forgotten to run "npm run make" before commiting the above mentioned pull request. Seems I have only run "npm run build" - means the two generated minified JS files have not been updated.
I'll fix this in my next pull request.

**Comment by mymth** [comment]
@xdev1  I got an idea and made some changes with calendar week number handling. What I did are:

- Made the `calendarWeek` option deprecated
- Removed the `getCalendarWeek ` option (Sorry!)
- Added a new option, `weekNumbers` that supports the 3 major week numbering systems listed in https://en.wikipedia.org/wiki/Week#Other_week_numbering_systems and user-defined function to calculate the week number of a date 
  The available options are:
  - `0`: None
  - `1`: ISO8601 week numbers
  - `2`: Western traditional week numbers
  - `3`: Middle Eastern week numbers
  - `4`: Guess from the `weekStart` option—if weekStart is:
    - `0` (Sunday) → Western traditional week numbers
    - `6` (Saturday) → Middle Eastern week numbers
    - Otherwise → ISO8601 week numbers
  - a function: User-defined week numbers. 
    The specs of the function are the same as `getCalendarWeek` —take a Date object and weekStart and return the week number of the date

I’m going to push the changes at some point in the future. Your program will stop working, but you should be able to fix it just by changing the option name.

FYI
