### ISSUE TITLE
The day of the week is set to a day before.

### ISSUE THREAD

**Issue by YankeeTube** [mymth/vanillajs-datepicker#93]
![image](https://user-images.githubusercontent.com/34546950/142854672-b5445de4-5de3-4187-a05d-ca03167a75b1.png)

today 2021.11.22 is monday but datepicker today is sunday

this is my option
```javascript
{
    autohide: true,
    orientation: 'bottom left',
    todayHighlight: true,
    format: 'yyyy.mm.dd',
    weekStart: 1,
}
```

**Comment by mymth** [comment]
I'm unable to reproduce the problem. it's also very hard to guess what can cause it.
Could you provide more details?

**Comment by YankeeTube** [comment]
@mymth  sorry my mistake... 
in the past, re define date.prototype.getDay(). It was a problem because of this.
