### ISSUE TITLE
tag new version

### ISSUE THREAD

**Issue by marc-mabe** [mymth/vanillajs-datepicker#94]
HI,

I want to use your nice package but unfortunately I can't because I need to mount the datepicker within unpoly layers.
This works fine with `container: up.layer.element` but the latest tagged version supports CSS selectors only as container option.
Also your documentation describes this as `CSS selector for the container element or the container element itself` which is not true at least for the latest version available.

**Comment by xdev1** [comment]
@marc-mabe #84 added the very new feature that option `container` can be both, a query string or a HMTL element itself. The sentence `"CSS selector for the container element or the container element itself"` in the documentation originates from the changes of the mentioned #84.  The documentation is newer than the latest tagged/released version of the `vanillajs-datepicker`, as you've mentioned above.
Maybe until a new release of `vanillajs-datepicker` will be published, the following entry in your `package.json` file could help you as a temporary workaround:  

```json
"dependencies": {
  ...
  "vanillajs-datepicker": "github:mymth/vanillajs-datepicker"
  ...
}
```

**Comment by marc-mabe** [comment]
Hi @xdev1,
yes this is working - I still hope there will be a release soon or at least before we would deploy our project to live as having an unstable dependency doesn't make my manager happy

**Comment by mymth** [comment]
I've just released the new version. So I'll close this.
